################################################################################################################
# Desc:      python3 base on centos7
# Author:    Jusheng Yao
# Server:    ip_addr
# Location:  /opt/project/service_app
# Usage:
#   Build:   docker build -t centos7 .
#   Run:     docker run -itd --name centos7 --restart always --privileged=true /usr/sbin/init
#   Enter:   docker exec -it centos7 /bin/bash
#   Gen:     bash ./gen_image.sh [版本信息, example: 1.0]
################################################################################################################
# ------------------------------------------------------------------------
#  create container image of development env
# ------------------------------------------------------------------------
FROM registry.cn-shanghai.aliyuncs.com/basic-dev/centos:7.6.1810 AS development

#维护者信息
# MAINTAINER alfred
LABEL maintainer="jusheng_yao@outlook.com"

# 标签
LABEL version="1.0"

RUN mkdir -p /opt/project/service_app
WORKDIR /opt/project/service_app

ADD . /opt/project/service_app

RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install -y epel-release deltarpm nodejs
RUN npm config set registry https://registry.npm.taobao.org --global && \
    npm config set disturl https://npm.taobao.org/dist --global
RUN npm install -g pm2

RUN pip3 config set global.index-url http://mirrors.aliyun.com/pypi/simple \
    && pip3 config set install.trusted-host mirrors.aliyun.com

# 安装依赖
RUN yum install -y dos2unix
RUN dos2unix requirements.txt
#RUN pip3 install --no-cache-dir -Ur requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
# 方法2 - 不中断执行 (bat脚本)
#RUN FOR /F "delims=\n" %f in (requirements.txt) DO pip3 install --no-cache-dir -U "%f"
#RUN FOR /F "delims=~" %f in (requirements.txt) do conda install --yes "%f"
# 方法3 - 不中断执行
RUN while read var; do [[ $var =~ ^#.* || $var == "" ]] && continue || pip3 install --no-cache-dir -U $var; done < requirements.txt
#RUN while read var; do [[ $var =~ ^#.* || $var == "" ]] && continue || conda install --yes $var; done < requirements.txt

# 如果有问题，请使用 'poetry_requires.txt' 这个依赖文件，使用下面的命令
#RUN pip3 install --no-cache-dir -r poetry_requires.txt
RUN echo -e "export PM2_HOME=/usr/local/node-`echo $(node -v | awk \"{print $1}\")`/out/lib/node_modules/pm2\nexport PATH=$PM2_HOME/bin:$PATH" >> /etc/profile
RUN source /etc/profile

ENTRYPOINT ["pm2","start","server.py","-x", "--interpreter", "python3","--no-daemon"]
CMD ["-o", "/logs/pm2_info.log", "-e", "./logs/pm2_error.log"]
# 允许外界访问容器的端口
EXPOSE 80 15668

# ------------------------------------------------------------------------
#  create container image of production env
# ------------------------------------------------------------------------
FROM centos:7.6.1810 AS production

LABEL maintainer="jusheng_yao@outlook.com"

WORKDIR /opt/project/service_app

COPY --from=development /opt/project/service_app ./

RUN set -ex \
    # 预安装所需组件
    && yum install -y wget tar libffi-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make initscripts \
    && wget https://www.python.org/ftp/python/3.7.5/Python-3.7.5.tgz \
    && tar -zxvf Python-3.7.5.tgz \
    && cd Python-3.7.5 \
    && ./configure prefix=/usr/local/python3 \
    && make \
    && make install \
    && make clean \
    && rm -rf /Python-3.7.5* \
    && yum install -y epel-release \
    && yum install -y python-pip
# 设置默认为python3
RUN set -ex \
    # 备份旧版本python
    && mv /usr/bin/python /usr/bin/python27 \
    && mv /usr/bin/pip /usr/bin/pip27 \
    # 配置默认为python3
    && ln -s /usr/local/python3/bin/python3.7 /usr/bin/python3 \
    && ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3
# 修复因修改python版本导致yum失效问题
RUN set -ex \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7#" /usr/bin/yum \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7#" /usr/libexec/urlgrabber-ext-down \
    && yum install -y deltarpm
# 基础环境配置
RUN set -ex \
    # 修改系统时区为东八区
    && rm -rf /etc/localtime \
    && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && yum install -y vim \
    # 安装定时任务组件
    && yum -y install cronie
# 支持中文
RUN yum install kde-l10n-Chinese -y
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8
ENV LC_ALL zh_CN.UTF-8

# 安装nodejs npm
RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install -y epel-release deltarpm nodejs
RUN npm config set registry https://registry.npm.taobao.org --global && \
    npm config set disturl https://npm.taobao.org/dist --global
RUN npm install -g pm2

# 更新pip版本
RUN pip3 config set global.index-url http://mirrors.aliyun.com/pypi/simple \
    && pip3 config set install.trusted-host mirrors.aliyun.com
RUN pip3 install --upgrade pip

RUN pip3 install -U pytest
# 安装依赖
RUN yum install -y dos2unix
RUN dos2unix requirements.txt
#RUN pip3 install --no-cache-dir -Ur requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
# 方法2 - 不中断执行 (bat脚本)
#RUN FOR /F "delims=\n" %f in (requirements.txt) DO pip3 install --no-cache-dir -U "%f"
#RUN FOR /F "delims=~" %f in (requirements.txt) do conda install --yes "%f"
# 方法3 - 不中断执行
RUN while read var; do [[ $var =~ ^#.* || $var == "" ]] && continue || pip3 install --no-cache-dir -U $var; done < requirements.txt
#RUN while read var; do [[ $var =~ ^#.* || $var == "" ]] && continue || conda install --yes $var; done < requirements.txt

EXPOSE 80 443 9000
CMD ["pm2", "start", "server.py", "--no-daemon", "-x", "--interpreter", "python3"]
#CMD ["bash", "bin/start.sh"]
