################################################################################################################
# Desc:    jupyter base on ubuntu
# Author:  Jusheng Yao
# Usage:
#   Build:   docker build -f Dockerfile-Server -t jupyter:v1.0 .
#   Run:     docker run -itd --name jupyter -v localpath:containerpath -p 8002:8888 \
#                       --restart always --privileged=true jupyter:v1.0 /usr/sbin/init
#   Enter:   docker exec -it jupyter /bin/bash
################################################################################################################
FROM yaojusheng/ubuntu:20.04

LABEL maintainer="jusheng_yao@outlook.com"

ENV TIME_ZONE=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive \
    WORKHOME=/usr/local

ARG user=alfred
ARG pwd=123456

WORKDIR ${WORKHOME}

COPY ../requirements.txt .

# install sudo passwd ...
RUN apt-get update && apt-get install -y sudo passwd openssh-client openssh-server logrotate cron less git

# add user/pwd
RUN useradd --create-home --no-log-init --shell /bin/bash ${user} \
    && adduser ${user} sudo \
    && echo "${user}:${pwd}" | chpasswd

# generate rsa
RUN rm -f /etc/ssh/ssh_host_rsa_key && ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N ""
RUN rm -f /etc/ssh/ssh_host_ecdsa_key && ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
RUN rm -f /etc/ssh/ssh_host_dsa_key && ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -N ""
RUN rm -f /etc/ssh/ssh_host_ed25519_key && ssh-keygen -q -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""

# modify ssh configuration
RUN sed -i 's/#UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config \
  && sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config \
  && sed -i 's/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g' /etc/ssh/sshd_config
RUN echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config \
  && echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

RUN echo "ssh_pid=`ps -ef | grep ssh| grep -v grep|awk '{print $2}'` \n \
         if [ -n \"$ssh_pid\" ];then \n /usr/sbin/sshd -D & \n fi" >> ${WORKHOME}/deploy

# RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get clean &&  apt update -y && apt upgrade -y
RUN apt install -y build-essential zlib1g-dev libbz2-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
RUN apt install -y vim iotop unzip zip make tcpdump telnet traceroute lrzsz tree curl iputils-ping net-tools
RUN apt install -y iproute2  ntpdate  nfs-kernel-server nfs-common openssl libpcre3 libpcre3-dev gcc openssh-server

RUN apt-get update -y && apt-get upgrade -y && apt-get clean && apt-get autoclean
RUN apt-get install -y apt-utils tzdata \
    && ln -fs /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime \
    && echo ${TIME_ZONE} > /etc/timezone

# install dependence of python3
RUN apt-get install -y libmysqlclient-dev python3-dev libpython3-dev python3-pip

RUN apt update
# compiled dependencies
RUN apt-get install -y gcc make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev

# install python:3.8
RUN apt update
RUN apt-get install -y software-properties-common  && add-apt-repository ppa:deadsnakes/ppa
RUN apt update && apt install -y python3.8

# change priority
RUN update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1

# RUN python3 -m ensurepip
RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools wheel --index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip3 config set global.index-url http://mirrors.aliyun.com/pypi/simple \
    && pip3 config set install.trusted-host mirrors.aliyun.com

# install jupyter
RUN pip3 install ipykernel jupyter jupyter_contrib_nbextensions jupyter_nbextensions_configurator
RUN jupyter contrib nbextension install --user && jupyter nbextensions_configurator enable --user

# install go && kernel
RUN wget https://dl.google.com/go/go1.17.5.linux-amd64.tar.gz && tar -C /usr/local -zxvf  go1.17.5.linux-amd64.tar.gz
# RUN export GOROOT=/usr/local/go && export PATH=$PATH:$GOROOT/bin
RUN echo "export GOROOT=/usr/local/go" >> ~/.bashrc && echo "export PATH=$PATH:$GOROOT/bin" >> ~/.bashrc && source ~/.bashrc
RUN go get -u github.com/gopherdata/gophernotes

EXPOSE 8888 80

CMD ["jupyter", "notebook", "--allow-root"]
