#!/bin/bash
# This script is used as the command supplied to GIT_ASKPASS as a way to supply username/password
# credentials to git, without having to use git credentials helpers, or having on-disk config.
# Author: JuSheng Yao

GIT_USERNAME=yaojusheng
GIT_PASSWORD=FBs2mxbrsgr6K99UHZHT

prompt=$(echo "$1" | tr '[:upper:]' '[:lower:]')

case "${prompt}" in
    username*)
		        echo "${GIT_USERNAME}"
					  ;;
		password*)
						echo "${GIT_PASSWORD}"
						;;
esac
