#!/bin/bash

set -e

cd $(dirname $0) || exit
dir=$(pwd)

log_color() {
  echo -e "\033[$@m [color test] num: $@ \033[0m"
}


printf "\033[36m [Current Directory]：\t%s\n\n\033[0m" "$dir"
echo -e "\033[35m ############################################################# \033[0m"
echo -e "\033[35m # 【Test】Start testing ... \033[0m"
echo -e "\033[35m ############################################################# \033[0m"

args=$(cat -n ./test.txt | grep -A 12 -i "example:" | grep -A 5 -i "ports:" | awk '{print $1}' | xargs)
echo -e "$args\n"

#arr=(`echo $args | tr ' ' ' '` )
#arr=($args)
arr=($(cat -n ./test.txt | grep -A 12 -i "example:" | grep -A 5 -i "ports:" | awk '{print $1}' | xargs))

echo "数组元素个数为: ${#arr[*]}"
echo "数组元素为: ${arr[@]}"

echo "第一个: ${arr[0]}"
echo "第二个: ${arr[1]}"
# echo "最后一个: ${arr[-1]}"
lastIndex=$((${#arr[@]}-1))
echo "最后一个: ${arr[lastIndex]}"

opts=("${@:2}")
opts="${opts[@]}"
# eval 将字符串转成 命令 执行

echo -e "\n第二个以后的参数：$opts\n"

for i in {30..40}
do
   log_color $i
done

echo -e "ENV name:             \033[1;45;32mTest\033[0m\n"
for i in {40..47}
do
   echo -e "Execute Command:      \033[3;$i;32mdocker-compose up $i\033[0m\n"
done
echo -e "Completed status:     \033[3;40;32mexecute successfully.\033[0m\n"
echo -e "Completed status:     \033[1;3;40;31mexecute failure.\033[0m\n"
echo -e "Completed status:     \033[1;3;7;31mexecute failure.\033[0m\n"
